import pymysql

def export_db_ddl(host, user, password, db_name):
    connection = None
    try:
        # 1. 建立数据库连接
        connection = pymysql.connect(
            host=host,
            user=user,
            password=password,
            database=db_name,
            charset='utf8mb4',
            cursorclass=pymysql.cursors.DictCursor
        )

        with connection.cursor() as cursor:
            # 2. 从 information_schema 获取所有基础表名称（排除 VIEW）
            sql_get_tables = """
                SELECT TABLE_NAME 
                FROM information_schema.TABLES 
                WHERE TABLE_SCHEMA = %s 
                AND TABLE_TYPE = 'BASE TABLE'
            """
            cursor.execute(sql_get_tables, (db_name,))
            tables = cursor.fetchall()

            if not tables:
                print(f"在数据库 '{db_name}' 中没有找到任何表。")
                return

            # 3. 准备写入文件
            with open(db_name + '_schema.sql', 'w', encoding='utf-8') as f:
                f.write(f"-- MySQL Database: {db_name} DDL Export\n")
                f.write(f"-- Generated by Python using pymysql\n\n")
                f.write("SET NAMES utf8mb4;\n")
                f.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")

                for table_dict in tables:
                    table_name = table_dict['TABLE_NAME']
                    
                    # 4. 获取每张表的 CREATE TABLE 语句
                    cursor.execute(f"SHOW CREATE TABLE `{table_name}`")
                    result = cursor.fetchone()
                    
                    # 'Create Table' 键包含了 DDL 字符串
                    ddl_string = result['Create Table']
                    
                    # 5. 格式化并写入文件
                    f.write(f"-- Table: {table_name}\n")
                    f.write(f"DROP TABLE IF EXISTS `{table_name}`;\n")
                    f.write(ddl_string + ";\n\n")
                    
                    print(f"成功导出表结构: {table_name}")
                f.write("SET FOREIGN_KEY_CHECKS = 1;\n")

            print(f"\n全部 DDL 已导出至: {db_name + '_schema.sql'}")

    except Exception as e:
        print(f"发生错误: {e}")
    finally:
        if connection:
            connection.close()

# --- 配置参数 ---
if __name__ == "__main__":
    config = {
        "host": "localhost",
        "user": "root",
        "password": "123123",
        "db_name": "",
    }

    export_db_ddl(**config)